CREATE TABLE IF NOT EXISTS propositions (
  id int NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE ,
  name VARCHAR (100) NOT NULL,
  email VARCHAR (100) NOT NULL,
  url VARCHAR (100),
  content VARCHAR (1000) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  ip VARCHAR (20),
  browser VARCHAR (200)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS complaints (
  id int NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE ,
  name VARCHAR (100) NOT NULL,
  email VARCHAR (100) NOT NULL,
  url VARCHAR (100),
  content VARCHAR (1000) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  ip VARCHAR (20),
  browser VARCHAR (200)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS users (
  id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR (100) NOT NULL,
  password VARCHAR (100) NOT NULL,
  permissions VARCHAR(200)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO users (username, password, permissions) VALUES ('admin', '$1$somethin$f3PxGtAYM8jWEyWGPrKsQ1', 'read,write');